New landing page
HackIllinois/site pull request #102
Opened 2023-07-01 18:19 UTC by anandani4136

2023-07-12 16:22 UTC, lasyaneti requested changes
gif not loading :(

2023-07-16 09:38 UTC, lasyaneti approved these changes

2023-07-17 05:44 UTC, lasyaneti approved these changes

2023-07-18 00:34 UTC, nrking0 approved these changes
Amazing! :)

2023-07-18 00:35 UTC, merged