Mentors page misc fixes
HackIllinois/site pull request #190
Opened 2024-02-09 21:57 UTC by tandebnath

2024-02-09 22:02 UTC, ashayp22 approved these changes

2024-02-09 22:02 UTC, lasyaneti commented
DONT MERGE YET

2024-02-09 22:05 UTC, ashayp22 requested changes
One small fix needed.

2024-02-09 22:05 UTC, ashayp22 commented on components/Navbar/Navbar.tsx
>                          {
Forgot to show Mentors above when the user is authenticated and registered.

2024-02-09 22:06 UTC, ashayp22 commented on components/Navbar/Navbar.tsx
>                          {
Instead, remove adding the Mentors page here and move it to `DEFAULT_NAVBAR_ITEMS` at the top of the screen.

2024-02-11 18:46 UTC, nrking0 approved these changes

2024-02-11 18:46 UTC, merged