Add progress bar
HackIllinois/site pull request #223
Opened 2024-11-03 18:50 UTC by BeckyBlake

<img width="872" alt="Screenshot 2024-11-03 at 12 49 57 PM" src="https://github.com/user-attachments/assets/9f3bc0b2-a23a-437c-a210-204e8faaf00a">

2024-11-05 06:17 UTC, J164 requested changes
This is a great start! I left a few comments to fix up before merging 🚀

2024-11-05 06:17 UTC, J164 commented on .prettierignore
> +public/registration/progress_bar/*.svg
Let's have prettier ignore the entire public/ directory

2024-11-05 06:17 UTC, J164 commented on components/ProgressBar/ProgressBar.module.scss
> +            transition: width 0.4s ease;
can we try ease-out and a longer animation for this? The current one seems a bit rushed

2024-11-05 06:17 UTC, J164 commented on components/ProgressBar/ProgressBar.module.scss
> +            img {
can we make the icons smaller when on mobile devices?

2024-11-06 22:12 UTC, J164 requested changes
There seems to be a small alignment issue:
![image](https://github.com/user-attachments/assets/09feeda2-735e-416b-bf99-f4f6d0e8794a)

2024-11-06 23:51 UTC, BeckyBlake commented
I've been having trouble with the moon and lightning bolt on the ends because if they're perfectly centered in their containers like the other symbols, then the bar peeks out on the ends.
<img width="877" alt="Screenshot 2024-11-06 at 5 48 57 PM" src="https://github.com/user-attachments/assets/95e30106-6c64-466a-a9cd-01c564bdeeef">

 i used negative margins on the moon and lightning to make it so that the bar doesn't peek out but as screen size decreases the difference in spacing becomes more noticeable. i'm not sure if you would consider this to be a significant difference in spacing or if it's fine
<img width="405" alt="Screenshot 2024-11-06 at 5 45 48 PM" src="https://github.com/user-attachments/assets/2931d88a-ec06-4b08-89ed-bb06069f463d">

2024-11-07 02:36 UTC, J164 commented
> I've been having trouble with the moon and lightning bolt on the ends because if they're perfectly centered in their containers like the other symbols, then the bar peeks out on the ends.
> 
> i used negative margins on the moon and lightning to make it so that the bar doesn't peek out but as screen size decreases the difference in spacing becomes more noticeable. i'm not sure if you would consider this to be a significant difference in spacing or if it's fine
 
This looks good for now. We can revisit if we have time before registration deadline

2024-11-11 01:29 UTC, J164 approved these changes
Awesome job on this! Looks great 🚀

2024-11-11 01:29 UTC, merged