Sponsorlanding srikar
HackIllinois/site pull request #67
Opened 2023-02-02 17:34 UTC by srikarmanikonda

2023-02-02 17:35 UTC, srikarmanikonda commented
I have no clue why the checks are failing.. But everything should look good

2023-02-06 06:43 UTC, aniketgargya requested changes
- Center the box
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/22971700/216900387-b2355319-0a29-4eb6-a867-396c9536b917.png">
- Center the sponsor label that lies on top of the big box

- Center the "Sponsors" text vertically
<img width="781" alt="image" src="https://user-images.githubusercontent.com/22971700/216901214-6762703f-41a2-49dc-bd70-202286576adc.png">
- The logos are pretty big on a laptop screen so maybe use a fixed with, and reduce the size of the logos on a mobile screen using breakpoints
- On a large screen the box intersects the footer, and on a small screen there is a large margin
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/22971700/216900901-2ae8c907-3597-42f9-9aa4-fd0118362e0c.png">
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/22971700/216900965-b8b4534b-d56b-4f9a-bf93-746701fc6417.png">

2023-02-12 20:18 UTC, ashayp22 requested changes
Section overall is solid, we just need a few minor tweaks in order to ensure that the sponsor section is readable and functional on all devices, especially phones.

2023-02-12 20:18 UTC, ashayp22 commented on src/components/sponsors/styles.module.scss
> +        margin-top: 1px; /* add some margin to separate the title from the rectangle */
The sponsor text is a bit too large on mobile. We can add a Media Query here to change the font-size for the sponsor text on Mobile Devices. Try `font-size: 25px.`

2023-02-12 20:18 UTC, ashayp22 commented on src/components/sponsors/styles.module.scss
> +        width: auto;
Instead of making the width `auto`, how about setting it to `90vw` so that it isn't the full width of the screen?

2023-02-12 20:18 UTC, ashayp22 commented on src/components/sponsors/styles.module.scss
> +.logo1{
The John Deere logo seems a bit pixelated. What about making the company logos smaller so they seem clearer to the website user?

2023-02-13 04:37 UTC, ashayp22 approved these changes

2023-02-13 05:01 UTC, anandani4136 approved these changes

2023-02-13 06:02 UTC, ashayp22 approved these changes

2023-02-14 04:44 UTC, merged